
package menuprincipal;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import gestorpeticiones.GestorPeticionesHTTP;
import numero.Numero;

import java.awt.*;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;

/**
 * @author Ismael
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */

    public final Color ROJO = new Color(0x720404);
    public final Color VERDE = new Color(0x017B00);
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBG = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblMostrarResumen = new javax.swing.JLabel();
        btnMostrarResumen = new javax.swing.JButton();
        tfComprobarNumeroPremiado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnComprobarNumeroPremiado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMuestraResultado = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBG.setBackground(new java.awt.Color(255, 255, 255));
        panelBG.setForeground(new java.awt.Color(255, 255, 255));
        panelBG.setToolTipText("");

        lblTitulo.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Premios Sorteo del niño");

        lblMostrarResumen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMostrarResumen.setText("Mostrar números premiados en el último sorteo");

        btnMostrarResumen.setText("Cargar números premiados");
        btnMostrarResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarResumenActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Comprobar si su número está premiado");

        btnComprobarNumeroPremiado.setText("Comprobar");
        btnComprobarNumeroPremiado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarNumeroPremiadoActionPerformed(evt);
            }
        });

        taMuestraResultado.setColumns(20);
        taMuestraResultado.setRows(5);
        jScrollPane1.setViewportView(taMuestraResultado);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBGLayout = new javax.swing.GroupLayout(panelBG);
        panelBG.setLayout(panelBGLayout);
        panelBGLayout.setHorizontalGroup(
                panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelBGLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelBGLayout.createSequentialGroup()
                                                .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblMostrarResumen))
                                                .addGap(79, 79, 79)
                                                .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnMostrarResumen)
                                                        .addGroup(panelBGLayout.createSequentialGroup()
                                                                .addComponent(tfComprobarNumeroPremiado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btnComprobarNumeroPremiado)))))
                                .addGap(0, 96, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBGLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpiar)
                                .addContainerGap())
        );
        panelBGLayout.setVerticalGroup(
                panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBGLayout.createSequentialGroup()
                                .addComponent(lblTitulo)
                                .addGap(32, 32, 32)
                                .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblMostrarResumen)
                                        .addComponent(btnMostrarResumen))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfComprobarNumeroPremiado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(btnComprobarNumeroPremiado))
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(btnLimpiar)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>


    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {
        taMuestraResultado.setBackground(Color.white);
        taMuestraResultado.setText("");
    }

    private void btnMostrarResumenActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void btnComprobarNumeroPremiadoActionPerformed(java.awt.event.ActionEvent evt) {
        String numeroIntroducido = tfComprobarNumeroPremiado.getText().toString();
        try {
            Numero numero = GestorPeticionesHTTP.comprobarNumero(numeroIntroducido);
            if (numero.getPremio() == 0) {
                taMuestraResultado.setForeground(ROJO);
                taMuestraResultado.setText("Lo sentimos, su número no ha obtenido ningún premio");
            } else {
                taMuestraResultado.setForeground(VERDE);
                taMuestraResultado.setText("SU NÚMERO HA GANADO " + numero.getPremio() + " €");
            }
        } catch (Exception e) {
            taMuestraResultado.setText("ERROR AL RECIBIR LA PETICIÓN");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {









        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnComprobarNumeroPremiado;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrarResumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMostrarResumen;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBG;
    private javax.swing.JTextArea taMuestraResultado;
    private javax.swing.JTextField tfComprobarNumeroPremiado;
    // End of variables declaration
}
